from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from orp_test_support import IsolatedTestCase


REPO_ROOT = Path(__file__).resolve().parents[1]
GUARD = REPO_ROOT / "scripts" / "npm-prepublish-guard.js"
RELEASE_TAG = REPO_ROOT / "scripts" / "npm-release-tag.js"


def _guard_env(**overrides: str | None) -> dict[str, str]:
    env = os.environ.copy()
    for key, value in overrides.items():
        if value is None:
            env.pop(key, None)
        else:
            env[key] = value
    return env


def _run_git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        cwd=str(root),
    )


def _git_init_main(root: Path) -> None:
    proc = _run_git(root, "init", "-b", "main")
    if proc.returncode == 0:
        return
    proc = _run_git(root, "init")
    if proc.returncode != 0:
        raise AssertionError(proc.stderr + "\n" + proc.stdout)
    proc = _run_git(root, "symbolic-ref", "HEAD", "refs/heads/main")
    if proc.returncode != 0:
        raise AssertionError(proc.stderr + "\n" + proc.stdout)


def _git_config_identity(root: Path) -> None:
    for key, value in [("user.name", "ORP Test"), ("user.email", "orp-test@example.com")]:
        proc = _run_git(root, "config", key, value)
        if proc.returncode != 0:
            raise AssertionError(proc.stderr + "\n" + proc.stdout)


def _git_commit_all(root: Path, message: str) -> None:
    _git_config_identity(root)
    if not (root / "package.json").exists():
        (root / "package.json").write_text(json.JSONEncoder().encode({"name":"open-research-protocol","version":"1.2.3","dependencies":{}}))
        (root / "package-lock.json").write_text(json.JSONEncoder().encode({"name":"open-research-protocol","version":"1.2.3","packages":{"":{"version":"1.2.3","dependencies":{}}}}))
    proc = _run_git(root, "add", "-A")
    if proc.returncode != 0:
        raise AssertionError(proc.stderr + "\n" + proc.stdout)
    proc = _run_git(root, "commit", "-m", message)
    if proc.returncode != 0:
        raise AssertionError(proc.stderr + "\n" + proc.stdout)


def _git_init_bare(root: Path) -> None:
    proc = subprocess.run(
        ["git", "init", "--bare"],
        capture_output=True,
        text=True,
        cwd=str(root),
    )
    if proc.returncode != 0:
        raise AssertionError(proc.stderr + "\n" + proc.stdout)


class NpmPublishGuardTests(IsolatedTestCase):
    def test_release_tag_keeps_prereleases_off_latest(self) -> None:
        node = shutil.which("node")
        if node is None:
            self.skipTest("node not found on PATH")

        prerelease = subprocess.run(
            [node, str(RELEASE_TAG), "0.5.0-rc.1"],
            capture_output=True,
            text=True,
        )
        stable = subprocess.run(
            [node, str(RELEASE_TAG), "0.5.0"],
            capture_output=True,
            text=True,
        )
        invalid = subprocess.run(
            [node, str(RELEASE_TAG), "release-candidate"],
            capture_output=True,
            text=True,
        )

        self.assertEqual(prerelease.returncode, 0, msg=prerelease.stderr)
        self.assertEqual(prerelease.stdout.strip(), "next")
        self.assertEqual(stable.returncode, 0, msg=stable.stderr)
        self.assertEqual(stable.stdout.strip(), "latest")
        self.assertNotEqual(invalid.returncode, 0)

    def test_package_manifest_excludes_generated_bytecode(self) -> None:
        npm = shutil.which("npm")
        if npm is None:
            self.skipTest("npm not found on PATH")

        with tempfile.TemporaryDirectory() as td:
            temp_root = Path(td)
            root = temp_root / "repo"
            shutil.copytree(
                REPO_ROOT,
                root,
                ignore=shutil.ignore_patterns(".git", "node_modules", ".venv", "*.tgz"),
            )
            bytecode_dir = root / "cli" / "__pycache__"
            bytecode_dir.mkdir(parents=True, exist_ok=True)
            (bytecode_dir / "orp.cpython-test.pyc").write_bytes(b"generated bytecode")
            (root / "scripts" / ".DS_Store").write_bytes(b"generated metadata")

            proc = subprocess.run(
                [
                    npm,
                    "pack",
                    "--dry-run",
                    "--json",
                    "--ignore-scripts",
                    "--cache",
                    str(temp_root / "npm-cache"),
                ],
                capture_output=True,
                text=True,
                cwd=str(root),
            )
            self.assertEqual(proc.returncode, 0, msg=proc.stderr + "\n" + proc.stdout)
            report = json.loads(proc.stdout)
            paths = [item["path"] for item in report[0]["files"]]
            blocked = [
                path
                for path in paths
                if "__pycache__" in path or path.endswith((".pyc", ".pyo", ".DS_Store"))
            ]
            self.assertEqual(blocked, [])
            self.assertIn("orp/hygiene-policy.json", paths)

    def test_guard_blocks_dirty_worktree(self) -> None:
        if shutil.which("node") is None:
            self.skipTest("node not found on PATH")

        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _git_init_main(root)
            (root / "README.md").write_text("clean\n", encoding="utf-8")
            _git_commit_all(root, "initial")
            (root / "README.md").write_text("dirty\n", encoding="utf-8")

            proc = subprocess.run(
                ["node", str(GUARD)],
                capture_output=True,
                text=True,
                cwd=str(root),
                env=_guard_env(GITHUB_ACTIONS=None),
            )
            self.assertNotEqual(proc.returncode, 0)
            self.assertIn("working tree is not clean", proc.stderr)

    def test_guard_blocks_unpushed_clean_head(self) -> None:
        if shutil.which("node") is None:
            self.skipTest("node not found on PATH")

        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _git_init_main(root)
            (root / "README.md").write_text("clean\n", encoding="utf-8")
            _git_commit_all(root, "initial")

            proc = subprocess.run(
                ["node", str(GUARD)],
                capture_output=True,
                text=True,
                cwd=str(root),
                env=_guard_env(GITHUB_ACTIONS=None),
            )
            self.assertNotEqual(proc.returncode, 0)
            self.assertIn("not present on any remote branch", proc.stderr)

    def test_guard_allows_clean_pushed_head(self) -> None:
        if shutil.which("node") is None:
            self.skipTest("node not found on PATH")

        with tempfile.TemporaryDirectory() as td:
            root = Path(td) / "repo"
            remote = Path(td) / "remote.git"
            root.mkdir(parents=True, exist_ok=True)
            remote.mkdir(parents=True, exist_ok=True)
            _git_init_main(root)
            _git_init_bare(remote)
            (root / "README.md").write_text("clean\n", encoding="utf-8")
            _git_commit_all(root, "initial")

            add_remote = _run_git(root, "remote", "add", "origin", str(remote))
            self.assertEqual(add_remote.returncode, 0, msg=add_remote.stderr + "\n" + add_remote.stdout)
            push = _run_git(root, "push", "-u", "origin", "main")
            self.assertEqual(push.returncode, 0, msg=push.stderr + "\n" + push.stdout)
            self.assertEqual(_run_git(root, "tag", "v1.2.3").returncode, 0)

            proc = subprocess.run(
                ["node", str(GUARD)],
                capture_output=True,
                text=True,
                cwd=str(root),
                env=_guard_env(GITHUB_ACTIONS=None),
            )
            self.assertEqual(proc.returncode, 0, msg=proc.stderr + "\n" + proc.stdout)

    def test_guard_rejects_missing_tag_lock_drift_and_non_main_even_on_actions(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td) / "repo"
            remote = Path(td) / "remote.git"
            root.mkdir(); remote.mkdir()
            _git_init_main(root); _git_init_bare(remote)
            _git_commit_all(root, "initial")
            self.assertEqual(_run_git(root, "remote", "add", "origin", str(remote)).returncode, 0)
            self.assertEqual(_run_git(root, "push", "-u", "origin", "main").returncode, 0)
            env = _guard_env(GITHUB_ACTIONS="true", GITHUB_REPOSITORY="SproutSeeds/orp")
            def check(message):
                result = subprocess.run(["node", str(GUARD)], cwd=root, env=env, capture_output=True, text=True)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(message, result.stderr)
            check("version tag must point")
            self.assertEqual(_run_git(root, "tag", "v1.2.3").returncode, 0)
            lock = json.loads((root / "package-lock.json").read_text())
            lock["version"] = "9.9.9"
            (root / "package-lock.json").write_text(json.JSONEncoder().encode(lock))
            _git_commit_all(root, "lock drift")
            self.assertEqual(_run_git(root, "push", "origin", "main").returncode, 0)
            check("package and lockfile")
            self.assertEqual(_run_git(root, "switch", "-c", "unmerged").returncode, 0)
            (root / "README.md").write_text("unmerged release")
            _git_commit_all(root, "unmerged")
            self.assertEqual(_run_git(root, "push", "origin", "unmerged").returncode, 0)
            check("contained in origin/main")


if __name__ == "__main__":
    unittest.main()
